#!/usr/bin/env bash

# https://misc.flogisoft.com/bash/tip_colors_and_formatting
# \e[0;90m == \e[1;30m

white=$(tput setaf 14)
for ((i = 1; i <= 256; i++)); do 
	color=$(tput setaf $i)
	if [[ $i -lt 10 ]]; then
		n="00$i"
	elif [[ $i -lt 100 ]]; then
		n="0$i"
	else
		n=$i
	fi
	echo "${white}${n}${color} This is some sample text."
done

tput sgr0