# Global settings
add_newline = false
command_timeout = 2000
palette = 'roperdot'

format = """
[$directory](bg:blue fg:pure_white)\
${custom.end_triangle}\
${env_var.GIT_STATUS_INFO} \
"""

# STATUS_INFO, DIR_STACK_INFO and GIT_STATUS_INFO are populated by functions in roperdot/roperdot-bootstrap

# Right side format - status, time, and directory stack depth  
right_format = """${custom.status_triangle}${env_var.STATUS_INFO}${custom.context_triangle}$username$hostname${custom.time_triangle}$time${custom.stack_triangle}${env_var.DIR_STACK_INFO}"""

[directory]
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[ $path ]($style)"
style = "bg:blue fg:pure_white"

# Command character (prompt symbol)
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Roperdot color palette
[palettes.roperdot]
# Base colors  
black = "#1e1f22"
blue = "#4d6d8b"
green = "#7a8431"
red = "#922f33"
yellow = "#d4804d"
orange = "#d4804d"
magenta = "#71527c"
cyan = "#4d7b74"
white = "#5d656d"

# Bright variants
bright_blue = "#6f90b0"
bright_green = "#a6b255"
bright_red = "#bf5053"
bright_yellow = "#ebbb61"
bright_magenta = "#a27fad"
bright_cyan = "#79b2a8"
bright_white = "#b9bcba"

pure_white = "#ffffff"

[env_var.GIT_STATUS_INFO]
format = "[$env_value](fg:none)"
variable = "GIT_STATUS_INFO"

[username]
show_always = true
format = "[$user]($style)"
style_user = "fg:yellow bg:black"

[hostname]
ssh_only = false
format = "[@$hostname ](fg:yellow bg:black)"
disabled = false

[time]
disabled = false
format = "[ $time ]($style)"
time_format = "%H:%M:%S"
style = "fg:black bg:white"

# Connecting triangles with proper colors
[custom.status_triangle]
when = true
command = "echo ''"
format = "[\uE0B2](fg:black)"  # Dark triangle from nothing to black background

[custom.context_triangle]  
when = true
command = "echo ''"
format = "[\uE0B3 ](fg:yellow bg:black)"

[custom.time_triangle]
when = true
command = "echo ''"
format = "[\uE0B2](fg:white bg:black)"  # Transition from black to light grey

[custom.stack_triangle]
when = "test $(dirs -p | wc -l) -ge 2"
command = "echo ''"  
format = "[\uE0B2](fg:magenta bg:bright_white)"  # Transition from light grey to magenta

[env_var.DIR_STACK_INFO]
format = "[$env_value](fg:none)"
variable = "DIR_STACK_INFO"

[env_var.STATUS_INFO]
format = "[$env_value](fg:none)"
variable = "STATUS_INFO"

[custom.end_triangle]
description = "Blue triangle for non-git directories"
command = "echo ''"  
when = "! git rev-parse --git-dir > /dev/null 2>&1"
format = "[\uE0B0](fg:blue)"